# Site settings
title: 阿阿阿阿丁的主页
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml.
baseurl: "/test/" # the subpath of your site, e.g. /blog/
url: "http://sonjasper.com/test" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
