# Site settings
title: 阿阿阿阿丁的主页
email: 
description: > # this means to ignore newlines until "baseurl:"
  Herzlich Willkommen!
baseurl: "/test" # the subpath of your site, e.g. /blog/
url: "http://sonjasper.com/test" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
